### ISSUE TITLE
Add support for Gw.dat sharing

### ISSUE THREAD

**Issue by AlexMacocian** [gwdevhub/Daybreak#329]
Implement different types of executables, to allow for deployed/linked executables that can share the same Gw.dat. 

Pro: Much more space efficient, most of the space footprint of Gw is the .dat file

Con: The game breaks if multiple executables sharing the same Gw.dat run at the same time and modify the Gw.dat. If there is no modification, the game runs fine. If one of the executables writes to Gw.dat, it will break all the other running executables and cause them to crash

**Comment by ChthonVII** [comment]
Will GW run if it's dat file is a read-only symlink? If so, what happens when it tries to write to the dat and can't?

**Comment by AlexMacocian** [comment]
I've tried this before. So, what happens is that as long as only one exe is running, it can write to the file and everything is fine.
When the second one starts, it won't be able to write to the file. As long as the .dat is complete (you don't need to download anything), it works.
But the moment it needs to download anything, it'll start behaving weird. It eventually leads to crashes, but first you'll see missing textures and stuff like that.

**Comment by AlexMacocian** [comment]
Won't implement. It's too dangerous and problematic
