### ISSUE TITLE
Client Crash on moving items in inventory

### ISSUE THREAD

**Issue by rebekkaqub** [gwdevhub/Daybreak#537]
Since one of the latest updates there has been an inconsistent but frequent issue of the game crashing whenever items are moved around in the player inventory. Doesn't seem to affect moving to and from Xunlai Chest.

**Comment by AlexMacocian** [comment]
Thanks for the report. I can replicate it. Seems to happen when in an instance, but for some reason doesn't happen in an outpost

**Comment by AlexMacocian** [comment]
Seems to be related to this
https://github.com/gwdevhub/GWCA/pull/3

**Comment by AlexMacocian** [comment]
Updated GWCA and it seems the bug is fixed
