### ISSUE TITLE
Quick launch / Arguments support ?

### ISSUE THREAD

**Issue by Ezelbys** [gwdevhub/Daybreak#683]
Hi,
Tried the tool for a few hours and really liked it, i just wanted to know if it's possible to launch the game directly without having to click again in the launcher. I checked the wiki and didn't find anything about it.

It's not a high priority request, but it would be nice to be able to launch it through steam / playnite and have your config loaded immediately.

**Comment by AlexMacocian** [comment]
Sure, I can add this feature.

How would you see it? It should launch the last LaunchConfiguration that you used only once, on startup of the application?

**Comment by AlexMacocian** [comment]
Okay so how about this? Each LaunchConfiguration has an id. I'll set up some arguments so that you can specify the what to launch by that id

**Comment by AlexMacocian** [comment]
#689

**Comment by AlexMacocian** [comment]
@Ezelbys Documented here: [Command Line Wiki](https://github.com/gwdevhub/Daybreak/wiki/Daybreak-Command-Line-Arguments)

Please update to the latest version and let me know if you encounter any issue.
