### ISSUE TITLE
Unable to inject GWCA into Guild Wars process

### ISSUE THREAD

**Issue by FromTheGrayve** [gwdevhub/Daybreak#716]
I keep getting this error when i try to use Daybreak. I assumed it was due to the new patch that came out for GW, but it's not been fixed with the .40 build. 

I can use Toolbox and Umod without Daybreak, so I don't think it's related to them.

**Comment by AlexMacocian** [comment]
That's interesting, can you give me a bit more details? It's working fine for me right now while running under normal user, without admin privileges.
When it fails to inject, can you still go back to the Launcher View and attach to the game?
Are you running it as admin?
Are there any special permissions set up on your PC that you're aware of?

**Comment by FromTheGrayve** [comment]
![bug2](https://github.com/gwdevhub/Daybreak/assets/56549939/463bb01d-006e-44f9-953b-a7ad647d8210)
![bug 1](https://github.com/gwdevhub/Daybreak/assets/56549939/55950ee0-715c-49ca-afe3-267aeab532a5)

The game will start, with password autofilled (Daybreak feature) and uMod loads. 
Toolbox does not load/start, I have to do that manually. 
I am running as an admin. 
I cannot 'attach' Daybreak (i was able to before the GW1 updates, so I know what you mean by attack), the options are Launch or Kill
The same issue occures when running as a non-Admin (I have to be admin for multi-launch support, that is why I default to admin, but I turned it off to test.

**Comment by FromTheGrayve** [comment]
The desired process number seems to change every time i try to launch, i have 11004, 7012, 20020, 11708, 4804, 8768, plus the ones above. The rest of the error text remains the same.

**Comment by AlexMacocian** [comment]
Okay first I'll clarify some details regarding the attach feature.
That one only works if you launch Guild Wars through Daybreak, because Daybreak on launch injects a GWCA plugin into GW that exposes this attach functionality. So you'll never be able to attach when launched from outside Daybreak.

I could try to add that functionality in a further release.

Now going back to your actual issue, tbh I don't know what's wrong. Seems like Daybreak is unable to actually inject anything into the guild wars executable it launches. 
I hope it's not getting blocked by the AV (which could happen, AVs don't like software that inject code into other processes)

As another try, could you go into Launcher settings, enable persistent logging then attempt to launch the game again? Once it fails, under Debug tab, you should see a Logs button. Go in there and in the top right there's a 'down arrow' button. Click on that to export your logs to a json file and upload it here pls.

**Comment by FromTheGrayve** [comment]
Oh, I didn't know that about the attach, sorry. Was just trying to test everything to give you data. I checked and Daybreak and GW1 are allowed through my firewall, and my AV is not reporting it is blocking any programs at or near the time i run it, so I don't think its that, but Im not a PC expert.  

Here is the log

[export lot for daybreak.json](https://github.com/gwdevhub/Daybreak/files/15246425/export.lot.for.daybreak.json)

**Comment by AlexMacocian** [comment]
No worries, I should probably explain better how it works on the wiki. It was really helpful that you gave me all those details. 

I took a quick glance at the logs and I see that it at least reports that toolbox is injected fine, which is even more strange given that you told me that toolbox is not loading. Something really weird is going on..

Sadly today I'm on the road travelling so I can't take a deeper look at your logs. I'll do that tomorrow. Sorry for the inconvenience with Daybreak 😢

**Comment by FromTheGrayve** [comment]
No worries, take your time. im on shift as well so can't test for 2 days anyway.

**Comment by AlexMacocian** [comment]
So I checked the logs. Sadly I don't have enough logs to tell what exactly happened but from what I can see, it looks like everything succeeds. Can you please check if you actually have a Daybreak.GWCA.dll file in the [DaybreakFolder]/GWCA/ folder?

I'll build a new release some time tomorrow to add some extra logging around the injection, specifically the GWCA plugin injection.

Finally, I've heard issues in the past from toolbox users that when Guild Wars updates, sometimes it breaks the exe in a way that when you launch it, it restarts before re-launching, effectively removing anything you inject on startup.

So ultimately, if the Daybreak.GWCA.dll is in its location, could you please reinstall Guild Wars? (you can keep the data file, you just need to reinstall the executable)

**Comment by AlexMacocian** [comment]
Hey, as an update, I've created a new version with improved logging (and some dependency updates)
https://github.com/gwdevhub/Daybreak/pull/722

**Comment by FromTheGrayve** [comment]
My Guild Wars folder contains a Daybreak folder, which has the daybreak.exe. Inside the Daybreak folder is a folder called GWCA and it contains the daybreak.gwca.dll.  I have not moved it at any point. If i am supposed to remove it from the GWCA folder and move it to the main daybreak folder let me know.

**Comment by FromTheGrayve** [comment]
I deleted the gw.exe and had steam repair the game. I get a new error when launching with daybreak. 

i am using daybreak version .41

![toolbox error](https://github.com/gwdevhub/Daybreak/assets/56549939/9ef937d3-c784-4864-94e4-31993e45090b)
![location of gwca](https://github.com/gwdevhub/Daybreak/assets/56549939/23d7cefc-85d9-47e2-b222-4d5deee2bcb4)
[NEW LOG on build .41.json](https://github.com/gwdevhub/Daybreak/files/15261572/NEW.LOG.on.build.41.json)


sorry for all the trouble, i really hope its not user error.  :(

**Comment by AlexMacocian** [comment]
Ah damn. Can you try to launch with toolbox disabled in mods?

**Comment by FromTheGrayve** [comment]
Afraid neither option works. It seems im the only one with this issue maybe i just just do a complete reinstall.

**Comment by FromTheGrayve** [comment]
Dont worry about it, i appreicate the effort you spend working on a free tool for a hobby

**Comment by AlexMacocian** [comment]
You get the same error in both options? As in, you get the GWToolboxpp API error even without toolbox being injected? I'm really surprised. That should never happen.

We can set up a discord session if you'd like and I can try to see what's going on

**Comment by FromTheGrayve** [comment]
Oh, I don't get the API error, sorry for the confusion. I mean i get the Daybreak cannot inject GWCA error message.

**Comment by AlexMacocian** [comment]
I've just found a pretty critical flaw in the gwca plugin that would cause it to hang when waiting for guild wars to give me the names of entities and titles.

This would cause the gwca plugin to stop responding after a while, resulting in Daybreak thinking that it doesn't work. 

I've set up a new release that should be available for update in like 30 minutes or so.. maybe it helps with your issue as well

**Comment by FromTheGrayve** [comment]
ill test it asap. 

`We can set up a discord session if you'd like and I can try to see what's going on`  I'm up and down from my PC so not sure I'd be around, but appreciate it.

**Comment by AlexMacocian** [comment]
Sure, let me know if/when you'd like to schedule a discord meeting.

If you eventually get it to work, I'll be really curious as to what you did, it might highlight issues with my code that I could fix

**Comment by FromTheGrayve** [comment]
Well, you probably won't be thrilled to hear this, but it seems to be entirely on my end/an issue with my install. 

I deleted Daybreak and it's entire folder, greated a new folder, did a fresh install of BOTH daybreak and GW1. It is currently able to launch and attach to that totally new install. I haven't tested it with Toolbox or uMod yet. I will update once I do.

**Comment by AlexMacocian** [comment]
So probably something is wrong with the original exe, but I'm unsure what. It's good that a least it works. Please test with toolbox and umod when you get the chance and let me know so I can close this issue

**Comment by AlexMacocian** [comment]
Hey @FromTheGrayve , any update? Have you tried it with toolbox and umod?

**Comment by FromTheGrayve** [comment]
Yes, they are working with the new complete reinstal. Sorry it took so long, got busy with work IRL and haven't had a chance to game

**Comment by AlexMacocian** [comment]
No worries. I just wanted to validate before I close this issue.

**Comment by AlexMacocian** [comment]
Can you check if the Daybreak.GWCA.dll exists in the Daybreak/GWCA folder?
It shouldn't be an absolute path since the dll is located relative to the
exe.

**Comment by AlexMacocian** [comment]
Oh sorry, I was checking it by email and I didn't notice. I'll take a look at it tomorrow

**Comment by AlexMacocian** [comment]
I see. Then I suppose the you're right, the fix will be to have an absolute
path there. Probably Steam launches Daybreak from a different folder than
where the exe is located

**Comment by FromTheGrayve** [comment]
I was using steam as well when i had these issues, so maybe it was the same problem?

**Comment by AlexMacocian** [comment]
Then it most probably was. I'll add some extra debug info to say where it is looking for the exe.

I'll also add a fix for these path issues. I was not considering that the app may be launched with the working directory in other places. There's multiple things that rely on the working directory being the root folder of Daybreak. I'll have to rework most of these paths.

**Comment by AlexMacocian** [comment]
So I'm making an attempt to fix this. The whole fix proved quite large because I had to find all occurrences in code where I reference a relative path and adjust it to go to the root folder of the project.
I hope I got them all in #758 
I tested the paths stuff by launching Daybreak from the Steam folder and as far as I can see, Daybreak resolves the relative paths in relation to where the executable is, not where the current directory is. This should solve the pathing issues.
Once the PR is merged, I'll release 0.9.9.44 and you can try it.

Let me know if you'll still have issues after the update
