### ISSUE TITLE
Installer cannot find package 

### ISSUE THREAD

**Issue by Narkant** [gwdevhub/Daybreak#780]
Just trying to install, but get this error when running the "Daybreak.Installer.Temp.exe" 

"Starting installation...
"Unable to find launcher package, aborting installlation." 

====================================================

Version: daybreakv0.9.9.45
webview2 runtime is installed. 

The .zip file was downloaded, extracted and tried to run installer. 

Also tried just running Daybreak.exe which launches the program, but unable to add the game paths without a bunch of errors popping up.

**Comment by AlexMacocian** [comment]
Did you solve your issue?
