### ISSUE TITLE
Adding new executables throws an exception

### ISSUE THREAD

**Issue by aGwGlob** [gwdevhub/Daybreak#783]
![image](https://github.com/user-attachments/assets/33f520d5-f112-4668-aac3-824106fe6d69)

steps to reproduce:
-three dots
-select gw executable
-click open

**Comment by aGwGlob** [comment]
it's first time testing daybreak launcher. Windows 11, running last version (btw,  last version release doesn't include all fails, just 2 folders, I had to download  the previous one and update from the launcher).

**Comment by AlexMacocian** [comment]
Oh wow, must be a bug introduced recently with the executable version checking and updating logic. I'll check it in a couple of hours.
As a workaround, you could go into the version view and downgrade like 3-4 versions before and set up your executables. 
That way, when you upgrade again, your executables will be saved and you should be able to use the version checking logic as well.

**Comment by AlexMacocian** [comment]
Found the issue. I prepared some code to implement update checking when you change the executable path but I forgot to implement it :(. Fixing it, an update should be available in an hour or so

**Comment by AlexMacocian** [comment]
Regarding the latest version zip file contains everything. Maybe you downloaded something else by mistake?
https://github.com/gwdevhub/Daybreak/releases/tag/v0.9.9.45
![image](https://github.com/user-attachments/assets/f75e5d11-d1ed-4b11-9434-460c52242ab2)

**Comment by AlexMacocian** [comment]
Once this job finishes, an update should be available in Daybreak
https://github.com/gwdevhub/Daybreak/actions/runs/9988835792/job/27606170926

**Comment by AlexMacocian** [comment]
Done. Please update and let me know if you still see issues

**Comment by AlexMacocian** [comment]
Closing this. Please let me know if you still see issues
